services:
  server:
    image: harshittjainn/nodejs-app:latest
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: netflix-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./server:/app/server
      - /app/node_modules
    restart: unless-stopped

  client:
    image: harshittjainn/reactjs-app:latest
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
    container_name: netflix-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped